//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.18 at 04:42:59 PM IST 
//


package com.virginvoyages.seaware.xml.ota.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Extension for the OTA_CruiseSailAvailRQ element.
 * 
 * <p>Java class for CruiseSailAvailRQExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CruiseSailAvailRQExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.versonix.com/ota}SearchAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CruiseSailAvailRQExtensionType", namespace = "http://www.versonix.com/ota")
public class CruiseSailAvailRQExtensionType {

    @XmlAttribute(name = "UseCacheInd")
    protected Boolean useCacheInd;
    @XmlAttribute(name = "IncludeCategoriesInd")
    protected Boolean includeCategoriesInd;

    /**
     * Gets the value of the useCacheInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseCacheInd() {
        return useCacheInd;
    }

    /**
     * Sets the value of the useCacheInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseCacheInd(Boolean value) {
        this.useCacheInd = value;
    }

    /**
     * Gets the value of the includeCategoriesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeCategoriesInd() {
        return includeCategoriesInd;
    }

    /**
     * Sets the value of the includeCategoriesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeCategoriesInd(Boolean value) {
        this.includeCategoriesInd = value;
    }

}
