//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.18 at 04:42:59 PM IST 
//


package com.virginvoyages.seaware.xml.ota.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeckType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeckType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Regular-OneLevelOnly"/>
 *     &lt;enumeration value="LowerLevel"/>
 *     &lt;enumeration value="UpperLevel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeckType")
@XmlEnum
public enum DeckType {

    @XmlEnumValue("Regular-OneLevelOnly")
    REGULAR_ONE_LEVEL_ONLY("Regular-OneLevelOnly"),
    @XmlEnumValue("LowerLevel")
    LOWER_LEVEL("LowerLevel"),
    @XmlEnumValue("UpperLevel")
    UPPER_LEVEL("UpperLevel");
    private final String value;

    DeckType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeckType fromValue(String v) {
        for (DeckType c: DeckType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
