//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.18 at 04:42:59 PM IST 
//


package com.virginvoyages.seaware.xml.ota.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the dynamic info type.
 * 
 * <p>Java class for DynamicInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DynamicInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DynamicFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DynamicField" maxOccurs="40" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Name" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
 *                           &lt;attribute name="StrVal" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
 *                           &lt;attribute name="DateVal" type="{http://www.opentravel.org/OTA/2003/05}DateOrDateTimeType" />
 *                           &lt;attribute name="NumVal" type="{http://www.opentravel.org/OTA/2003/05}NumericStringLength1to16" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DynamicInfoType", namespace = "http://www.versonix.com/ota", propOrder = {
    "dynamicFields"
})
public class DynamicInfoType {

    @XmlElement(name = "DynamicFields", required = true)
    protected DynamicInfoType.DynamicFields dynamicFields;

    /**
     * Gets the value of the dynamicFields property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicInfoType.DynamicFields }
     *     
     */
    public DynamicInfoType.DynamicFields getDynamicFields() {
        return dynamicFields;
    }

    /**
     * Sets the value of the dynamicFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicInfoType.DynamicFields }
     *     
     */
    public void setDynamicFields(DynamicInfoType.DynamicFields value) {
        this.dynamicFields = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DynamicField" maxOccurs="40" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Name" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
     *                 &lt;attribute name="StrVal" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
     *                 &lt;attribute name="DateVal" type="{http://www.opentravel.org/OTA/2003/05}DateOrDateTimeType" />
     *                 &lt;attribute name="NumVal" type="{http://www.opentravel.org/OTA/2003/05}NumericStringLength1to16" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dynamicField"
    })
    public static class DynamicFields {

        @XmlElement(name = "DynamicField", namespace = "http://www.versonix.com/ota")
        protected List<DynamicInfoType.DynamicFields.DynamicField> dynamicField;

        /**
         * Gets the value of the dynamicField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dynamicField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDynamicField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DynamicInfoType.DynamicFields.DynamicField }
         * 
         * 
         */
        public List<DynamicInfoType.DynamicFields.DynamicField> getDynamicField() {
            if (dynamicField == null) {
                dynamicField = new ArrayList<DynamicInfoType.DynamicFields.DynamicField>();
            }
            return this.dynamicField;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Name" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
         *       &lt;attribute name="StrVal" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
         *       &lt;attribute name="DateVal" type="{http://www.opentravel.org/OTA/2003/05}DateOrDateTimeType" />
         *       &lt;attribute name="NumVal" type="{http://www.opentravel.org/OTA/2003/05}NumericStringLength1to16" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DynamicField {

            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "StrVal")
            protected String strVal;
            @XmlAttribute(name = "DateVal")
            protected String dateVal;
            @XmlAttribute(name = "NumVal")
            protected String numVal;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the strVal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStrVal() {
                return strVal;
            }

            /**
             * Sets the value of the strVal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStrVal(String value) {
                this.strVal = value;
            }

            /**
             * Gets the value of the dateVal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateVal() {
                return dateVal;
            }

            /**
             * Sets the value of the dateVal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateVal(String value) {
                this.dateVal = value;
            }

            /**
             * Gets the value of the numVal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumVal() {
                return numVal;
            }

            /**
             * Sets the value of the numVal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumVal(String value) {
                this.numVal = value;
            }

        }

    }

}
