//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.18 at 04:42:59 PM IST 
//


package com.virginvoyages.seaware.xml.ota.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Can specify reservation id, allotment agreement id, client id, travel agent id, etc., depending on Type (see OTA code list UIT).
 * 
 * <p>Java class for UniqueID_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UniqueID_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompanyName" type="{http://www.opentravel.org/OTA/2003/05}CompanyNameType" minOccurs="0"/>
 *         &lt;element name="TPA_Extensions" type="{http://www.versonix.com/ota}UniqueIDExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}UniqueID_Group"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UniqueID_Type", propOrder = {
    "companyName",
    "tpaExtensions"
})
@XmlSeeAlso({
    com.virginvoyages.seaware.xml.ota.data.OTACruisePaymentRQ.ReservationPayment.ReservationID.class,
    com.virginvoyages.seaware.xml.ota.data.OTACruiseCancellationPricingRQ.ReservationID.class,
    com.virginvoyages.seaware.xml.ota.data.ProfileType.UserID.class,
    ReservationIDType.class,
    com.virginvoyages.seaware.xml.ota.data.OTACancelRQ.UniqueID.class,
    com.virginvoyages.seaware.xml.ota.data.OTACruiseBookingDocumentRS.ReservationID.class,
    com.virginvoyages.seaware.xml.ota.data.OTAReadRQ.ReadRequests.ProfileReadRequest.UniqueID.class,
    com.virginvoyages.seaware.xml.ota.data.VehicleReservationRQAdditionalInfoType.Reference.class,
    com.virginvoyages.seaware.xml.ota.data.AuthorizationType.BookingReferenceID.class,
    com.virginvoyages.seaware.xml.ota.data.AirReservationType.BookingReferenceID.class,
    com.virginvoyages.seaware.xml.ota.data.RoomStaysType.RoomStay.Reference.class,
    com.virginvoyages.seaware.xml.ota.data.VehicleReservationSummaryType.ConfID.class,
    com.virginvoyages.seaware.xml.ota.data.VehicleSegmentCoreType.ConfID.class,
    com.virginvoyages.seaware.xml.ota.data.SourceType.RequestorID.class,
    com.virginvoyages.seaware.xml.ota.data.VehicleAvailCoreType.Reference.class
})
public class UniqueIDType {

    @XmlElement(name = "CompanyName")
    protected CompanyNameType companyName;
    @XmlElement(name = "TPA_Extensions")
    protected UniqueIDExtensionType tpaExtensions;
    @XmlAttribute(name = "URL")
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlAttribute(name = "Type", required = true)
    protected String type;
    @XmlAttribute(name = "Instance")
    protected String instance;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "ID_Context")
    protected String idContext;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyNameType }
     *     
     */
    public CompanyNameType getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyNameType }
     *     
     */
    public void setCompanyName(CompanyNameType value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the tpaExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIDExtensionType }
     *     
     */
    public UniqueIDExtensionType getTPAExtensions() {
        return tpaExtensions;
    }

    /**
     * Sets the value of the tpaExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIDExtensionType }
     *     
     */
    public void setTPAExtensions(UniqueIDExtensionType value) {
        this.tpaExtensions = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstance(String value) {
        this.instance = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDContext() {
        return idContext;
    }

    /**
     * Sets the value of the idContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDContext(String value) {
        this.idContext = value;
    }

}
