//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.16 at 12:25:21 AM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Total element for the GetAvailDining_OUT message
 * 
 * <p>Java class for AvailDiningTotals complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailDiningTotals">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="AvlBase" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="AvlParty" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="UsageTotals" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Abs" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Wgt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailDiningTotals", propOrder = {

})
public class AvailDiningTotals {

    @XmlElement(name = "Total", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger total;
    @XmlElement(name = "AvlBase")
    protected double avlBase;
    @XmlElement(name = "AvlParty")
    protected Double avlParty;
    @XmlElement(name = "UsageTotals")
    protected AvailDiningTotals.UsageTotals usageTotals;

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotal(BigInteger value) {
        this.total = value;
    }

    /**
     * Gets the value of the avlBase property.
     * 
     */
    public double getAvlBase() {
        return avlBase;
    }

    /**
     * Sets the value of the avlBase property.
     * 
     */
    public void setAvlBase(double value) {
        this.avlBase = value;
    }

    /**
     * Gets the value of the avlParty property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAvlParty() {
        return avlParty;
    }

    /**
     * Sets the value of the avlParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAvlParty(Double value) {
        this.avlParty = value;
    }

    /**
     * Gets the value of the usageTotals property.
     * 
     * @return
     *     possible object is
     *     {@link AvailDiningTotals.UsageTotals }
     *     
     */
    public AvailDiningTotals.UsageTotals getUsageTotals() {
        return usageTotals;
    }

    /**
     * Sets the value of the usageTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailDiningTotals.UsageTotals }
     *     
     */
    public void setUsageTotals(AvailDiningTotals.UsageTotals value) {
        this.usageTotals = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Abs" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Wgt" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abs",
        "wgt"
    })
    public static class UsageTotals {

        @XmlElement(name = "Abs", required = true)
        protected BigInteger abs;
        @XmlElement(name = "Wgt")
        protected double wgt;

        /**
         * Gets the value of the abs property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAbs() {
            return abs;
        }

        /**
         * Sets the value of the abs property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAbs(BigInteger value) {
            this.abs = value;
        }

        /**
         * Gets the value of the wgt property.
         * 
         */
        public double getWgt() {
            return wgt;
        }

        /**
         * Sets the value of the wgt property.
         * 
         */
        public void setWgt(double value) {
            this.wgt = value;
        }

    }

}
