//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompBookMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CompBookMode">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="Mandatory"/>
 *     &lt;enumeration value="CanInclude"/>
 *     &lt;enumeration value="CanExclude"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CompBookMode")
@XmlEnum
public enum CompBookMode {

    @XmlEnumValue("Mandatory")
    MANDATORY("Mandatory"),
    @XmlEnumValue("CanInclude")
    CAN_INCLUDE("CanInclude"),
    @XmlEnumValue("CanExclude")
    CAN_EXCLUDE("CanExclude");
    private final String value;

    CompBookMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CompBookMode fromValue(String v) {
        for (CompBookMode c: CompBookMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
