//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 02:38:45 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}DbSearchBase_OUT">
 *       &lt;sequence>
 *         &lt;element name="ShipFacilities" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ShipFacility" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="Ship" type="{}ShipCode"/>
 *                             &lt;element name="FacilityType" type="{}FacilityType"/>
 *                             &lt;element name="FacilityCode" type="{}FacilityCode"/>
 *                             &lt;element name="FacilityName">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;>FacilityName">
 *                                     &lt;attGroup ref="{}TranslAttrGroup"/>
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Rank" type="{}Rank" minOccurs="0"/>
 *                             &lt;element name="DeckNumber" type="{}DeckNumber" minOccurs="0"/>
 *                             &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                             &lt;element name="MaxOccupancy" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                             &lt;element name="DateRange" type="{}DateRange"/>
 *                             &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
 *                             &lt;element name="DynamicFields" type="{}DynamicFields" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shipFacilities"
})
@XmlRootElement(name = "DbSearch_OUT")
public class DbSearchOUT
    extends DbSearchBaseOUT
{

    @XmlElement(name = "ShipFacilities")
    protected DbSearchOUT.ShipFacilities shipFacilities;

    /**
     * Gets the value of the shipFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link DbSearchOUT.ShipFacilities }
     *     
     */
    public DbSearchOUT.ShipFacilities getShipFacilities() {
        return shipFacilities;
    }

    /**
     * Sets the value of the shipFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSearchOUT.ShipFacilities }
     *     
     */
    public void setShipFacilities(DbSearchOUT.ShipFacilities value) {
        this.shipFacilities = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ShipFacility" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="Ship" type="{}ShipCode"/>
     *                   &lt;element name="FacilityType" type="{}FacilityType"/>
     *                   &lt;element name="FacilityCode" type="{}FacilityCode"/>
     *                   &lt;element name="FacilityName">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;>FacilityName">
     *                           &lt;attGroup ref="{}TranslAttrGroup"/>
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Rank" type="{}Rank" minOccurs="0"/>
     *                   &lt;element name="DeckNumber" type="{}DeckNumber" minOccurs="0"/>
     *                   &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *                   &lt;element name="MaxOccupancy" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *                   &lt;element name="DateRange" type="{}DateRange"/>
     *                   &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
     *                   &lt;element name="DynamicFields" type="{}DynamicFields" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shipFacility"
    })
    public static class ShipFacilities {

        @XmlElement(name = "ShipFacility")
        protected List<DbSearchOUT.ShipFacilities.ShipFacility> shipFacility;

        /**
         * Gets the value of the shipFacility property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shipFacility property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShipFacility().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DbSearchOUT.ShipFacilities.ShipFacility }
         * 
         * 
         */
        public List<DbSearchOUT.ShipFacilities.ShipFacility> getShipFacility() {
            if (shipFacility == null) {
                shipFacility = new ArrayList<DbSearchOUT.ShipFacilities.ShipFacility>();
            }
            return this.shipFacility;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="Ship" type="{}ShipCode"/>
         *         &lt;element name="FacilityType" type="{}FacilityType"/>
         *         &lt;element name="FacilityCode" type="{}FacilityCode"/>
         *         &lt;element name="FacilityName">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;>FacilityName">
         *                 &lt;attGroup ref="{}TranslAttrGroup"/>
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Rank" type="{}Rank" minOccurs="0"/>
         *         &lt;element name="DeckNumber" type="{}DeckNumber" minOccurs="0"/>
         *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
         *         &lt;element name="MaxOccupancy" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
         *         &lt;element name="DateRange" type="{}DateRange"/>
         *         &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
         *         &lt;element name="DynamicFields" type="{}DynamicFields" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class ShipFacility {

            @XmlElement(name = "Ship", required = true)
            protected String ship;
            @XmlElement(name = "FacilityType", required = true)
            protected String facilityType;
            @XmlElement(name = "FacilityCode", required = true)
            protected String facilityCode;
            @XmlElement(name = "FacilityName", required = true)
            protected DbSearchOUT.ShipFacilities.ShipFacility.FacilityName facilityName;
            @XmlElement(name = "Rank")
            protected BigInteger rank;
            @XmlElement(name = "DeckNumber")
            protected BigInteger deckNumber;
            @XmlElement(name = "Size")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger size;
            @XmlElement(name = "MaxOccupancy")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger maxOccupancy;
            @XmlElement(name = "DateRange", required = true)
            protected DateRange dateRange;
            @XmlElement(name = "Comments")
            protected String comments;
            @XmlElement(name = "DynamicFields")
            protected DynamicFields dynamicFields;

            /**
             * Gets the value of the ship property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShip() {
                return ship;
            }

            /**
             * Sets the value of the ship property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShip(String value) {
                this.ship = value;
            }

            /**
             * Gets the value of the facilityType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFacilityType() {
                return facilityType;
            }

            /**
             * Sets the value of the facilityType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFacilityType(String value) {
                this.facilityType = value;
            }

            /**
             * Gets the value of the facilityCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFacilityCode() {
                return facilityCode;
            }

            /**
             * Sets the value of the facilityCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFacilityCode(String value) {
                this.facilityCode = value;
            }

            /**
             * Gets the value of the facilityName property.
             * 
             * @return
             *     possible object is
             *     {@link DbSearchOUT.ShipFacilities.ShipFacility.FacilityName }
             *     
             */
            public DbSearchOUT.ShipFacilities.ShipFacility.FacilityName getFacilityName() {
                return facilityName;
            }

            /**
             * Sets the value of the facilityName property.
             * 
             * @param value
             *     allowed object is
             *     {@link DbSearchOUT.ShipFacilities.ShipFacility.FacilityName }
             *     
             */
            public void setFacilityName(DbSearchOUT.ShipFacilities.ShipFacility.FacilityName value) {
                this.facilityName = value;
            }

            /**
             * Gets the value of the rank property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRank() {
                return rank;
            }

            /**
             * Sets the value of the rank property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRank(BigInteger value) {
                this.rank = value;
            }

            /**
             * Gets the value of the deckNumber property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDeckNumber() {
                return deckNumber;
            }

            /**
             * Sets the value of the deckNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDeckNumber(BigInteger value) {
                this.deckNumber = value;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSize() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSize(BigInteger value) {
                this.size = value;
            }

            /**
             * Gets the value of the maxOccupancy property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMaxOccupancy() {
                return maxOccupancy;
            }

            /**
             * Sets the value of the maxOccupancy property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMaxOccupancy(BigInteger value) {
                this.maxOccupancy = value;
            }

            /**
             * Gets the value of the dateRange property.
             * 
             * @return
             *     possible object is
             *     {@link DateRange }
             *     
             */
            public DateRange getDateRange() {
                return dateRange;
            }

            /**
             * Sets the value of the dateRange property.
             * 
             * @param value
             *     allowed object is
             *     {@link DateRange }
             *     
             */
            public void setDateRange(DateRange value) {
                this.dateRange = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

            /**
             * Gets the value of the dynamicFields property.
             * 
             * @return
             *     possible object is
             *     {@link DynamicFields }
             *     
             */
            public DynamicFields getDynamicFields() {
                return dynamicFields;
            }

            /**
             * Sets the value of the dynamicFields property.
             * 
             * @param value
             *     allowed object is
             *     {@link DynamicFields }
             *     
             */
            public void setDynamicFields(DynamicFields value) {
                this.dynamicFields = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;>FacilityName">
             *       &lt;attGroup ref="{}TranslAttrGroup"/>
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class FacilityName {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "Language")
                protected String language;
                @XmlAttribute(name = "Translation")
                protected String translation;

                /**
                 * Ship facility name
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the language property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguage() {
                    return language;
                }

                /**
                 * Sets the value of the language property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguage(String value) {
                    this.language = value;
                }

                /**
                 * Gets the value of the translation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTranslation() {
                    return translation;
                }

                /**
                 * Sets the value of the translation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTranslation(String value) {
                    this.translation = value;
                }

            }

        }

    }

}
