//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 02:38:45 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}DbSearchBase_IN">
 *       &lt;sequence>
 *         &lt;element name="AccContexts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PackageType" type="{}PkgType" minOccurs="0"/>
 *         &lt;element name="PackageTypeAttributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="PackageType" type="{}PkgCode" minOccurs="0"/>
 *                   &lt;element name="PackageTypes" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;whiteSpace value="collapse"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AttrType" type="{}LongCode" minOccurs="0"/>
 *                   &lt;element name="AttrCode" type="{}LongCode" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PackageTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="PackageType" type="{}PkgType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipFacilities" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="FacilityID" type="{}RecordID" minOccurs="0"/>
 *                   &lt;element name="Ship" type="{}ShipCode" minOccurs="0"/>
 *                   &lt;element name="FacilityType" type="{}FacilityType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accContexts",
    "packageType",
    "packageTypeAttributes",
    "packageTypes",
    "shipFacilities"
})
@XmlRootElement(name = "DbSearch_IN")
public class DbSearchIN
    extends DbSearchBaseIN
{

    @XmlElement(name = "AccContexts")
    protected DbSearchIN.AccContexts accContexts;
    @XmlElement(name = "PackageType")
    protected String packageType;
    @XmlElement(name = "PackageTypeAttributes")
    protected DbSearchIN.PackageTypeAttributes packageTypeAttributes;
    @XmlElement(name = "PackageTypes")
    protected DbSearchIN.PackageTypes packageTypes;
    @XmlElement(name = "ShipFacilities")
    protected DbSearchIN.ShipFacilities shipFacilities;

    /**
     * Gets the value of the accContexts property.
     * 
     * @return
     *     possible object is
     *     {@link DbSearchIN.AccContexts }
     *     
     */
    public DbSearchIN.AccContexts getAccContexts() {
        return accContexts;
    }

    /**
     * Sets the value of the accContexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSearchIN.AccContexts }
     *     
     */
    public void setAccContexts(DbSearchIN.AccContexts value) {
        this.accContexts = value;
    }

    /**
     * Gets the value of the packageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageType(String value) {
        this.packageType = value;
    }

    /**
     * Gets the value of the packageTypeAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link DbSearchIN.PackageTypeAttributes }
     *     
     */
    public DbSearchIN.PackageTypeAttributes getPackageTypeAttributes() {
        return packageTypeAttributes;
    }

    /**
     * Sets the value of the packageTypeAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSearchIN.PackageTypeAttributes }
     *     
     */
    public void setPackageTypeAttributes(DbSearchIN.PackageTypeAttributes value) {
        this.packageTypeAttributes = value;
    }

    /**
     * Gets the value of the packageTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DbSearchIN.PackageTypes }
     *     
     */
    public DbSearchIN.PackageTypes getPackageTypes() {
        return packageTypes;
    }

    /**
     * Sets the value of the packageTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSearchIN.PackageTypes }
     *     
     */
    public void setPackageTypes(DbSearchIN.PackageTypes value) {
        this.packageTypes = value;
    }

    /**
     * Gets the value of the shipFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link DbSearchIN.ShipFacilities }
     *     
     */
    public DbSearchIN.ShipFacilities getShipFacilities() {
        return shipFacilities;
    }

    /**
     * Sets the value of the shipFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSearchIN.ShipFacilities }
     *     
     */
    public void setShipFacilities(DbSearchIN.ShipFacilities value) {
        this.shipFacilities = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AccContexts {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="PackageType" type="{}PkgCode" minOccurs="0"/>
     *         &lt;element name="PackageTypes" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;whiteSpace value="collapse"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AttrType" type="{}LongCode" minOccurs="0"/>
     *         &lt;element name="AttrCode" type="{}LongCode" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PackageTypeAttributes {

        @XmlElement(name = "PackageType")
        protected String packageType;
        @XmlElement(name = "PackageTypes")
        protected String packageTypes;
        @XmlElement(name = "AttrType")
        protected String attrType;
        @XmlElement(name = "AttrCode")
        protected String attrCode;

        /**
         * Gets the value of the packageType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackageType() {
            return packageType;
        }

        /**
         * Sets the value of the packageType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackageType(String value) {
            this.packageType = value;
        }

        /**
         * Gets the value of the packageTypes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackageTypes() {
            return packageTypes;
        }

        /**
         * Sets the value of the packageTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackageTypes(String value) {
            this.packageTypes = value;
        }

        /**
         * Gets the value of the attrType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrType() {
            return attrType;
        }

        /**
         * Sets the value of the attrType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrType(String value) {
            this.attrType = value;
        }

        /**
         * Gets the value of the attrCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrCode() {
            return attrCode;
        }

        /**
         * Sets the value of the attrCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrCode(String value) {
            this.attrCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="PackageType" type="{}PkgType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PackageTypes {

        @XmlElement(name = "PackageType")
        protected String packageType;

        /**
         * Gets the value of the packageType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackageType() {
            return packageType;
        }

        /**
         * Sets the value of the packageType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackageType(String value) {
            this.packageType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="FacilityID" type="{}RecordID" minOccurs="0"/>
     *         &lt;element name="Ship" type="{}ShipCode" minOccurs="0"/>
     *         &lt;element name="FacilityType" type="{}FacilityType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class ShipFacilities {

        @XmlElement(name = "FacilityID")
        protected Integer facilityID;
        @XmlElement(name = "Ship")
        protected String ship;
        @XmlElement(name = "FacilityType")
        protected String facilityType;

        /**
         * Gets the value of the facilityID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFacilityID() {
            return facilityID;
        }

        /**
         * Sets the value of the facilityID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFacilityID(Integer value) {
            this.facilityID = value;
        }

        /**
         * Gets the value of the ship property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShip() {
            return ship;
        }

        /**
         * Sets the value of the ship property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShip(String value) {
            this.ship = value;
        }

        /**
         * Gets the value of the facilityType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFacilityType() {
            return facilityType;
        }

        /**
         * Sets the value of the facilityType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFacilityType(String value) {
            this.facilityType = value;
        }

    }

}
