//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 02:38:45 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Options on DbSearch message level
 * 
 * <p>Java class for DbSearchOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DbSearchOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MaxRows" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ActiveOnly" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="CountOnly" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="SortItems" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SortItem" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="NodeName" type="{}NodeName"/>
 *                             &lt;element name="OrderBy">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="Mode">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="Columns"/>
 *                                           &lt;enumeration value="Nodes"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IncludeElements" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{}NodeName" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FilterBySets" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="IncludeDisplayRanks" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="MaxDuration" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MaxCost" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ForceTranslation" type="{}Boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DbSearchOptions", propOrder = {

})
public class DbSearchOptions {

    @XmlElement(name = "MaxRows")
    protected BigInteger maxRows;
    @XmlElement(name = "ActiveOnly", defaultValue = "Y")
    protected Boolean activeOnly;
    @XmlElement(name = "CountOnly")
    protected Boolean countOnly;
    @XmlElement(name = "SortItems")
    protected DbSearchOptions.SortItems sortItems;
    @XmlList
    @XmlElement(name = "IncludeElements")
    protected List<String> includeElements;
    @XmlElement(name = "FilterBySets")
    protected Boolean filterBySets;
    @XmlElement(name = "IncludeDisplayRanks", defaultValue = "N")
    protected Boolean includeDisplayRanks;
    @XmlElement(name = "MaxDuration")
    protected BigInteger maxDuration;
    @XmlElement(name = "MaxCost")
    protected BigInteger maxCost;
    @XmlElement(name = "ForceTranslation", defaultValue = "N")
    protected Boolean forceTranslation;

    /**
     * Gets the value of the maxRows property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxRows() {
        return maxRows;
    }

    /**
     * Sets the value of the maxRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxRows(BigInteger value) {
        this.maxRows = value;
    }

    /**
     * Gets the value of the activeOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getActiveOnly() {
        return activeOnly;
    }

    /**
     * Sets the value of the activeOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActiveOnly(Boolean value) {
        this.activeOnly = value;
    }

    /**
     * Gets the value of the countOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCountOnly() {
        return countOnly;
    }

    /**
     * Sets the value of the countOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCountOnly(Boolean value) {
        this.countOnly = value;
    }

    /**
     * Gets the value of the sortItems property.
     * 
     * @return
     *     possible object is
     *     {@link DbSearchOptions.SortItems }
     *     
     */
    public DbSearchOptions.SortItems getSortItems() {
        return sortItems;
    }

    /**
     * Sets the value of the sortItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSearchOptions.SortItems }
     *     
     */
    public void setSortItems(DbSearchOptions.SortItems value) {
        this.sortItems = value;
    }

    /**
     * Gets the value of the includeElements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includeElements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludeElements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIncludeElements() {
        if (includeElements == null) {
            includeElements = new ArrayList<String>();
        }
        return this.includeElements;
    }

    /**
     * Gets the value of the filterBySets property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFilterBySets() {
        return filterBySets;
    }

    /**
     * Sets the value of the filterBySets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterBySets(Boolean value) {
        this.filterBySets = value;
    }

    /**
     * Gets the value of the includeDisplayRanks property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIncludeDisplayRanks() {
        return includeDisplayRanks;
    }

    /**
     * Sets the value of the includeDisplayRanks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeDisplayRanks(Boolean value) {
        this.includeDisplayRanks = value;
    }

    /**
     * Gets the value of the maxDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDuration() {
        return maxDuration;
    }

    /**
     * Sets the value of the maxDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDuration(BigInteger value) {
        this.maxDuration = value;
    }

    /**
     * Gets the value of the maxCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxCost() {
        return maxCost;
    }

    /**
     * Sets the value of the maxCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxCost(BigInteger value) {
        this.maxCost = value;
    }

    /**
     * Gets the value of the forceTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getForceTranslation() {
        return forceTranslation;
    }

    /**
     * Sets the value of the forceTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForceTranslation(Boolean value) {
        this.forceTranslation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SortItem" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="NodeName" type="{}NodeName"/>
     *                   &lt;element name="OrderBy">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="Mode">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="Columns"/>
     *                                 &lt;enumeration value="Nodes"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sortItem"
    })
    public static class SortItems {

        @XmlElement(name = "SortItem", required = true)
        protected List<DbSearchOptions.SortItems.SortItem> sortItem;

        /**
         * Gets the value of the sortItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sortItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSortItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DbSearchOptions.SortItems.SortItem }
         * 
         * 
         */
        public List<DbSearchOptions.SortItems.SortItem> getSortItem() {
            if (sortItem == null) {
                sortItem = new ArrayList<DbSearchOptions.SortItems.SortItem>();
            }
            return this.sortItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="NodeName" type="{}NodeName"/>
         *         &lt;element name="OrderBy">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="Mode">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="Columns"/>
         *                       &lt;enumeration value="Nodes"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class SortItem {

            @XmlElement(name = "NodeName", required = true)
            protected String nodeName;
            @XmlElement(name = "OrderBy", required = true)
            protected DbSearchOptions.SortItems.SortItem.OrderBy orderBy;

            /**
             * Gets the value of the nodeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNodeName() {
                return nodeName;
            }

            /**
             * Sets the value of the nodeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNodeName(String value) {
                this.nodeName = value;
            }

            /**
             * Gets the value of the orderBy property.
             * 
             * @return
             *     possible object is
             *     {@link DbSearchOptions.SortItems.SortItem.OrderBy }
             *     
             */
            public DbSearchOptions.SortItems.SortItem.OrderBy getOrderBy() {
                return orderBy;
            }

            /**
             * Sets the value of the orderBy property.
             * 
             * @param value
             *     allowed object is
             *     {@link DbSearchOptions.SortItems.SortItem.OrderBy }
             *     
             */
            public void setOrderBy(DbSearchOptions.SortItems.SortItem.OrderBy value) {
                this.orderBy = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="Mode">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="Columns"/>
             *             &lt;enumeration value="Nodes"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class OrderBy {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "Mode")
                protected String mode;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the mode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMode() {
                    return mode;
                }

                /**
                 * Sets the value of the mode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMode(String value) {
                    this.mode = value;
                }

            }

        }

    }

}
