//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgHeader" type="{}MsgHeader"/>
 *         &lt;choice>
 *           &lt;element name="AvailPackages" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="AvailPackage" type="{}AvailSecondaryPkg" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SailLocations" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="SailLocation" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Type" type="{}LocationType"/>
 *                               &lt;element name="Code" type="{}Code" minOccurs="0"/>
 *                               &lt;element name="Name" type="{}ShortComment" minOccurs="0"/>
 *                               &lt;element name="ShipArrival" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                               &lt;element name="ShipDeparture" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                               &lt;element name="AvailPackages" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="AvailPackage" type="{}AvailSecondaryPkg" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Errors" type="{}Errors" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgHeader",
    "availPackages",
    "sailLocations",
    "errors"
})
@XmlRootElement(name = "GetAvailShorex_OUT")
public class GetAvailShorexOUT {

    @XmlElement(name = "MsgHeader", required = true)
    protected MsgHeader msgHeader;
    @XmlElement(name = "AvailPackages")
    protected GetAvailShorexOUT.AvailPackages availPackages;
    @XmlElement(name = "SailLocations")
    protected GetAvailShorexOUT.SailLocations sailLocations;
    @XmlElement(name = "Errors")
    protected Errors errors;

    /**
     * Gets the value of the msgHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader }
     *     
     */
    public MsgHeader getMsgHeader() {
        return msgHeader;
    }

    /**
     * Sets the value of the msgHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader }
     *     
     */
    public void setMsgHeader(MsgHeader value) {
        this.msgHeader = value;
    }

    /**
     * Gets the value of the availPackages property.
     * 
     * @return
     *     possible object is
     *     {@link GetAvailShorexOUT.AvailPackages }
     *     
     */
    public GetAvailShorexOUT.AvailPackages getAvailPackages() {
        return availPackages;
    }

    /**
     * Sets the value of the availPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAvailShorexOUT.AvailPackages }
     *     
     */
    public void setAvailPackages(GetAvailShorexOUT.AvailPackages value) {
        this.availPackages = value;
    }

    /**
     * Gets the value of the sailLocations property.
     * 
     * @return
     *     possible object is
     *     {@link GetAvailShorexOUT.SailLocations }
     *     
     */
    public GetAvailShorexOUT.SailLocations getSailLocations() {
        return sailLocations;
    }

    /**
     * Sets the value of the sailLocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAvailShorexOUT.SailLocations }
     *     
     */
    public void setSailLocations(GetAvailShorexOUT.SailLocations value) {
        this.sailLocations = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link Errors }
     *     
     */
    public Errors getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Errors }
     *     
     */
    public void setErrors(Errors value) {
        this.errors = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AvailPackage" type="{}AvailSecondaryPkg" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "availPackage"
    })
    public static class AvailPackages {

        @XmlElement(name = "AvailPackage")
        protected List<AvailSecondaryPkg> availPackage;

        /**
         * Gets the value of the availPackage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the availPackage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAvailPackage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AvailSecondaryPkg }
         * 
         * 
         */
        public List<AvailSecondaryPkg> getAvailPackage() {
            if (availPackage == null) {
                availPackage = new ArrayList<AvailSecondaryPkg>();
            }
            return this.availPackage;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SailLocation" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Type" type="{}LocationType"/>
     *                   &lt;element name="Code" type="{}Code" minOccurs="0"/>
     *                   &lt;element name="Name" type="{}ShortComment" minOccurs="0"/>
     *                   &lt;element name="ShipArrival" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                   &lt;element name="ShipDeparture" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                   &lt;element name="AvailPackages" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AvailPackage" type="{}AvailSecondaryPkg" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sailLocation"
    })
    public static class SailLocations {

        @XmlElement(name = "SailLocation")
        protected List<GetAvailShorexOUT.SailLocations.SailLocation> sailLocation;

        /**
         * Gets the value of the sailLocation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sailLocation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSailLocation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetAvailShorexOUT.SailLocations.SailLocation }
         * 
         * 
         */
        public List<GetAvailShorexOUT.SailLocations.SailLocation> getSailLocation() {
            if (sailLocation == null) {
                sailLocation = new ArrayList<GetAvailShorexOUT.SailLocations.SailLocation>();
            }
            return this.sailLocation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Type" type="{}LocationType"/>
         *         &lt;element name="Code" type="{}Code" minOccurs="0"/>
         *         &lt;element name="Name" type="{}ShortComment" minOccurs="0"/>
         *         &lt;element name="ShipArrival" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *         &lt;element name="ShipDeparture" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *         &lt;element name="AvailPackages" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AvailPackage" type="{}AvailSecondaryPkg" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "code",
            "name",
            "shipArrival",
            "shipDeparture",
            "availPackages"
        })
        public static class SailLocation {

            @XmlElement(name = "Type", required = true)
            protected LocationType type;
            @XmlElement(name = "Code")
            protected String code;
            @XmlElement(name = "Name")
            protected String name;
            @XmlElement(name = "ShipArrival")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar shipArrival;
            @XmlElement(name = "ShipDeparture")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar shipDeparture;
            @XmlElement(name = "AvailPackages")
            protected GetAvailShorexOUT.SailLocations.SailLocation.AvailPackages availPackages;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link LocationType }
             *     
             */
            public LocationType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link LocationType }
             *     
             */
            public void setType(LocationType value) {
                this.type = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the shipArrival property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getShipArrival() {
                return shipArrival;
            }

            /**
             * Sets the value of the shipArrival property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setShipArrival(XMLGregorianCalendar value) {
                this.shipArrival = value;
            }

            /**
             * Gets the value of the shipDeparture property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getShipDeparture() {
                return shipDeparture;
            }

            /**
             * Sets the value of the shipDeparture property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setShipDeparture(XMLGregorianCalendar value) {
                this.shipDeparture = value;
            }

            /**
             * Gets the value of the availPackages property.
             * 
             * @return
             *     possible object is
             *     {@link GetAvailShorexOUT.SailLocations.SailLocation.AvailPackages }
             *     
             */
            public GetAvailShorexOUT.SailLocations.SailLocation.AvailPackages getAvailPackages() {
                return availPackages;
            }

            /**
             * Sets the value of the availPackages property.
             * 
             * @param value
             *     allowed object is
             *     {@link GetAvailShorexOUT.SailLocations.SailLocation.AvailPackages }
             *     
             */
            public void setAvailPackages(GetAvailShorexOUT.SailLocations.SailLocation.AvailPackages value) {
                this.availPackages = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AvailPackage" type="{}AvailSecondaryPkg" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "availPackage"
            })
            public static class AvailPackages {

                @XmlElement(name = "AvailPackage")
                protected List<AvailSecondaryPkg> availPackage;

                /**
                 * Gets the value of the availPackage property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the availPackage property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAvailPackage().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link AvailSecondaryPkg }
                 * 
                 * 
                 */
                public List<AvailSecondaryPkg> getAvailPackage() {
                    if (availPackage == null) {
                        availPackage = new ArrayList<AvailSecondaryPkg>();
                    }
                    return this.availPackage;
                }

            }

        }

    }

}
