//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InventoryResult.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InventoryResult">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="GTY"/>
 *     &lt;enumeration value="WTL"/>
 *     &lt;enumeration value="NO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InventoryResult")
@XmlEnum
public enum InventoryResult {


    /**
     * A physical inventory slot was allocated (cabin, room, etc.).
     * 
     */
    OK,

    /**
     * Physical space is guaranteed according to requested parameters though exact inventory slot is not allocated yet. For example, cabin of requested category is reserved but exact cabin number is not allocated yet.
     * 
     */
    GTY,

    /**
     * Allocation is put in the waitlist.
     * 
     */
    WTL,

    /**
     * Either nothing is available or impossible to book there, for example, NO can be indicated for categories, where all cabins have capacity less than party size.
     * 
     */
    NO;

    public String value() {
        return name();
    }

    public static InventoryResult fromValue(String v) {
        return valueOf(v);
    }

}
