//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Inventory usage totals
 * 
 * <p>Java class for InventoryUsage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InventoryUsage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Result" type="{}AvailabilityResult"/>
 *         &lt;element name="Abs" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Wgt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventoryUsage", propOrder = {
    "result",
    "abs",
    "wgt"
})
public class InventoryUsage {

    @XmlElement(name = "Result", required = true)
    protected InventoryResult result;
    @XmlElement(name = "Abs", required = true)
    protected BigInteger abs;
    @XmlElement(name = "Wgt")
    protected double wgt;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryResult }
     *     
     */
    public InventoryResult getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryResult }
     *     
     */
    public void setResult(InventoryResult value) {
        this.result = value;
    }

    /**
     * Gets the value of the abs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAbs() {
        return abs;
    }

    /**
     * Sets the value of the abs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAbs(BigInteger value) {
        this.abs = value;
    }

    /**
     * Gets the value of the wgt property.
     * 
     */
    public double getWgt() {
        return wgt;
    }

    /**
     * Sets the value of the wgt property.
     * 
     */
    public void setWgt(double value) {
        this.wgt = value;
    }

}
