//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="15"/>
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="CITY"/>
 *     &lt;enumeration value="PORT"/>
 *     &lt;enumeration value="AIRPORT"/>
 *     &lt;enumeration value="HOTEL"/>
 *     &lt;enumeration value="AIR-HOTEL"/>
 *     &lt;enumeration value="SHIP"/>
 *     &lt;enumeration value="BUS STOP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocationType")
@XmlEnum
public enum LocationType {

    CITY("CITY"),
    PORT("PORT"),
    AIRPORT("AIRPORT"),
    HOTEL("HOTEL"),
    @XmlEnumValue("AIR-HOTEL")
    AIR_HOTEL("AIR-HOTEL"),
    SHIP("SHIP"),
    @XmlEnumValue("BUS STOP")
    BUS_STOP("BUS STOP");
    private final String value;

    LocationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocationType fromValue(String v) {
        for (LocationType c: LocationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
