//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.06 at 12:32:24 PM EDT 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Message header
 * 
 * <p>Java class for MsgHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{}APIVersion"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="SessionGUID" type="{}GUID"/>
 *           &lt;element name="CallerInfo">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="UserInfo" type="{}UserInfo"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="MessageID" type="{}MessageID" minOccurs="0"/>
 *         &lt;element name="Language" type="{}LanguageCode" minOccurs="0"/>
 *         &lt;element name="ValidateMode" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="DebugOptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ShowDbSearchSQL" type="{}Boolean" minOccurs="0"/>
 *                   &lt;element name="TraceXSLT" type="{}Boolean" minOccurs="0"/>
 *                   &lt;element name="DebugFolder" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="250"/>
 *                         &lt;whiteSpace value="collapse"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgHeader", propOrder = {
    "version",
    "sessionGUID",
    "callerInfo",
    "messageID",
    "language",
    "validateMode",
    "debugOptions"
})
public class MsgHeader {

    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "SessionGUID")
    protected String sessionGUID;
    @XmlElement(name = "CallerInfo")
    protected MsgHeader.CallerInfo callerInfo;
    @XmlElement(name = "MessageID")
    protected String messageID;
    @XmlElement(name = "Language")
    protected String language;
    @XmlElement(name = "ValidateMode")
    protected Boolean validateMode;
    @XmlElement(name = "DebugOptions")
    protected MsgHeader.DebugOptions debugOptions;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the sessionGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionGUID() {
        return sessionGUID;
    }

    /**
     * Sets the value of the sessionGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionGUID(String value) {
        this.sessionGUID = value;
    }

    /**
     * Gets the value of the callerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader.CallerInfo }
     *     
     */
    public MsgHeader.CallerInfo getCallerInfo() {
        return callerInfo;
    }

    /**
     * Sets the value of the callerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader.CallerInfo }
     *     
     */
    public void setCallerInfo(MsgHeader.CallerInfo value) {
        this.callerInfo = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the validateMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getValidateMode() {
        return validateMode;
    }

    /**
     * Sets the value of the validateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidateMode(Boolean value) {
        this.validateMode = value;
    }

    /**
     * Gets the value of the debugOptions property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHeader.DebugOptions }
     *     
     */
    public MsgHeader.DebugOptions getDebugOptions() {
        return debugOptions;
    }

    /**
     * Sets the value of the debugOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHeader.DebugOptions }
     *     
     */
    public void setDebugOptions(MsgHeader.DebugOptions value) {
        this.debugOptions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UserInfo" type="{}UserInfo"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userInfo"
    })
    public static class CallerInfo {

        @XmlElement(name = "UserInfo", required = true)
        protected UserInfo userInfo;

        /**
         * Gets the value of the userInfo property.
         * 
         * @return
         *     possible object is
         *     {@link UserInfo }
         *     
         */
        public UserInfo getUserInfo() {
            return userInfo;
        }

        /**
         * Sets the value of the userInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserInfo }
         *     
         */
        public void setUserInfo(UserInfo value) {
            this.userInfo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ShowDbSearchSQL" type="{}Boolean" minOccurs="0"/>
     *         &lt;element name="TraceXSLT" type="{}Boolean" minOccurs="0"/>
     *         &lt;element name="DebugFolder" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="250"/>
     *               &lt;whiteSpace value="collapse"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class DebugOptions {

        @XmlElement(name = "ShowDbSearchSQL")
        protected Boolean showDbSearchSQL;
        @XmlElement(name = "TraceXSLT")
        protected Boolean traceXSLT;
        @XmlElement(name = "DebugFolder")
        protected String debugFolder;

        /**
         * Gets the value of the showDbSearchSQL property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean getShowDbSearchSQL() {
            return showDbSearchSQL;
        }

        /**
         * Sets the value of the showDbSearchSQL property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setShowDbSearchSQL(Boolean value) {
            this.showDbSearchSQL = value;
        }

        /**
         * Gets the value of the traceXSLT property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean getTraceXSLT() {
            return traceXSLT;
        }

        /**
         * Sets the value of the traceXSLT property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setTraceXSLT(Boolean value) {
            this.traceXSLT = value;
        }

        /**
         * Gets the value of the debugFolder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDebugFolder() {
            return debugFolder;
        }

        /**
         * Sets the value of the debugFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDebugFolder(String value) {
            this.debugFolder = value;
        }

    }

}
