//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 01:43:15 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ObjectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="30"/>
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="COUPON"/>
 *     &lt;enumeration value="AGENCY"/>
 *     &lt;enumeration value="AGENT"/>
 *     &lt;enumeration value="CLIENT"/>
 *     &lt;enumeration value="HOUSEHOLD"/>
 *     &lt;enumeration value="TRAVEL-WITH"/>
 *     &lt;enumeration value="RES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ObjectType")
@XmlEnum
public enum ObjectType {

    COUPON("COUPON"),
    AGENCY("AGENCY"),
    AGENT("AGENT"),
    CLIENT("CLIENT"),
    HOUSEHOLD("HOUSEHOLD"),
    @XmlEnumValue("TRAVEL-WITH")
    TRAVEL_WITH("TRAVEL-WITH"),
    RES("RES");
    private final String value;

    ObjectType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ObjectType fromValue(String v) {
        for (ObjectType c: ObjectType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
