//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PkgBookMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PkgBookMode">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="PRE-BOOK ONLY"/>
 *     &lt;enumeration value="PRE-SELL ONLY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PkgBookMode")
@XmlEnum
public enum PkgBookMode {

    @XmlEnumValue("PRE-BOOK ONLY")
    PRE_BOOK_ONLY("PRE-BOOK ONLY"),
    @XmlEnumValue("PRE-SELL ONLY")
    PRE_SELL_ONLY("PRE-SELL ONLY");
    private final String value;

    PkgBookMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PkgBookMode fromValue(String v) {
        for (PkgBookMode c: PkgBookMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
