//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes package component
 * 
 * <p>Java class for PkgComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PkgComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompRecordID" type="{}RecordID"/>
 *         &lt;element name="SeqN" type="{}SeqNumber"/>
 *         &lt;element name="Type" type="{}ComponentType"/>
 *         &lt;element name="BaseType" type="{}ComponentType"/>
 *         &lt;element name="Code" type="{}ComponentCode" minOccurs="0"/>
 *         &lt;element name="SubCode1" type="{}CompSubCode" minOccurs="0"/>
 *         &lt;element name="SubCode2" type="{}CompSubCode" minOccurs="0"/>
 *         &lt;element name="SubCode3" type="{}CompSubCode" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="Sail" type="{}SailRange" minOccurs="0"/>
 *             &lt;element name="DateTime" type="{}DateTimeRange" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="Day" minOccurs="0">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                       &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="Time" type="{}TimeRange" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Location" type="{}LocationRange" minOccurs="0"/>
 *         &lt;element name="BookMode" type="{}CompBookMode" minOccurs="0"/>
 *         &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
 *         &lt;element name="Description" type="{}LongComment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PkgComponent", propOrder = {
    "compRecordID",
    "seqN",
    "type",
    "baseType",
    "code",
    "subCode1",
    "subCode2",
    "subCode3",
    "sail",
    "dateTime",
    "day",
    "time",
    "location",
    "bookMode",
    "comments",
    "description"
})
public class PkgComponent {

    @XmlElement(name = "CompRecordID")
    protected int compRecordID;
    @XmlElement(name = "SeqN", required = true)
    protected BigInteger seqN;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "BaseType", required = true)
    protected String baseType;
    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "SubCode1")
    protected String subCode1;
    @XmlElement(name = "SubCode2")
    protected String subCode2;
    @XmlElement(name = "SubCode3")
    protected String subCode3;
    @XmlElement(name = "Sail")
    protected SailRange sail;
    @XmlElement(name = "DateTime")
    protected DateTimeRange dateTime;
    @XmlElement(name = "Day")
    protected PkgComponent.Day day;
    @XmlElement(name = "Time")
    protected TimeRange time;
    @XmlElement(name = "Location")
    protected LocationRange location;
    @XmlElement(name = "BookMode")
    protected CompBookMode bookMode;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the compRecordID property.
     * 
     */
    public int getCompRecordID() {
        return compRecordID;
    }

    /**
     * Sets the value of the compRecordID property.
     * 
     */
    public void setCompRecordID(int value) {
        this.compRecordID = value;
    }

    /**
     * Gets the value of the seqN property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeqN() {
        return seqN;
    }

    /**
     * Sets the value of the seqN property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeqN(BigInteger value) {
        this.seqN = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the baseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseType() {
        return baseType;
    }

    /**
     * Sets the value of the baseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseType(String value) {
        this.baseType = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the subCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCode1() {
        return subCode1;
    }

    /**
     * Sets the value of the subCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCode1(String value) {
        this.subCode1 = value;
    }

    /**
     * Gets the value of the subCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCode2() {
        return subCode2;
    }

    /**
     * Sets the value of the subCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCode2(String value) {
        this.subCode2 = value;
    }

    /**
     * Gets the value of the subCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCode3() {
        return subCode3;
    }

    /**
     * Sets the value of the subCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCode3(String value) {
        this.subCode3 = value;
    }

    /**
     * Gets the value of the sail property.
     * 
     * @return
     *     possible object is
     *     {@link SailRange }
     *     
     */
    public SailRange getSail() {
        return sail;
    }

    /**
     * Sets the value of the sail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailRange }
     *     
     */
    public void setSail(SailRange value) {
        this.sail = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRange }
     *     
     */
    public DateTimeRange getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRange }
     *     
     */
    public void setDateTime(DateTimeRange value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link PkgComponent.Day }
     *     
     */
    public PkgComponent.Day getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgComponent.Day }
     *     
     */
    public void setDay(PkgComponent.Day value) {
        this.day = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link TimeRange }
     *     
     */
    public TimeRange getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeRange }
     *     
     */
    public void setTime(TimeRange value) {
        this.time = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationRange }
     *     
     */
    public LocationRange getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationRange }
     *     
     */
    public void setLocation(LocationRange value) {
        this.location = value;
    }

    /**
     * Gets the value of the bookMode property.
     * 
     * @return
     *     possible object is
     *     {@link CompBookMode }
     *     
     */
    public CompBookMode getBookMode() {
        return bookMode;
    }

    /**
     * Sets the value of the bookMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompBookMode }
     *     
     */
    public void setBookMode(CompBookMode value) {
        this.bookMode = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "from",
        "to"
    })
    public static class Day {

        @XmlElement(name = "From", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger from;
        @XmlElement(name = "To", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger to;

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFrom(BigInteger value) {
            this.from = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTo(BigInteger value) {
            this.to = value;
        }

    }

}
