//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Describes package as a whole
 * 
 * <p>Java class for PkgDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PkgDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PackageID" type="{}RecordID"/>
 *         &lt;element name="Vacation" type="{}DateTimeRange"/>
 *         &lt;element name="Location" type="{}LocationRange" minOccurs="0"/>
 *         &lt;element name="Type" type="{}PkgType"/>
 *         &lt;element name="Code" type="{}PkgCode"/>
 *         &lt;element name="Name" type="{}PkgName" minOccurs="0"/>
 *         &lt;element name="ProductType" type="{}ProductType"/>
 *         &lt;element name="SailID" type="{}RecordID" minOccurs="0"/>
 *         &lt;element name="LandDays" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SailDays" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrePostMode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}Code">
 *               &lt;enumeration value="PRE"/>
 *               &lt;enumeration value="POST"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TransfersOnly" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="NeedsVendorConfirm" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="Destination" type="{}DestinationCode" minOccurs="0"/>
 *         &lt;element name="Destinations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Destination" type="{}DestinationCode" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Season" type="{}SeasonCode" minOccurs="0"/>
 *         &lt;element name="PkgComment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>ShortComment">
 *                 &lt;attGroup ref="{}TranslAttrGroup"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PkgTypeComment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>ShortComment">
 *                 &lt;attGroup ref="{}TranslAttrGroup"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Description" type="{}LongComment" minOccurs="0"/>
 *         &lt;element name="Components" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Component" type="{}PkgComponent" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IsActive" type="{}Boolean"/>
 *         &lt;element name="IsFake" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="ColorFIT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ColorGroup" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Colors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Color" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DateRange" type="{}DateRange"/>
 *                             &lt;choice>
 *                               &lt;element name="ColorFIT" minOccurs="0">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="15"/>
 *                                     &lt;whiteSpace value="collapse"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="ColorGroup" minOccurs="0">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="15"/>
 *                                     &lt;whiteSpace value="collapse"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                             &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShorexMode" type="{}PkgBookMode" minOccurs="0"/>
 *         &lt;element name="ShorexTiming" type="{}Code" minOccurs="0"/>
 *         &lt;element name="InitialStatus" type="{}PkgStatus" minOccurs="0"/>
 *         &lt;element name="AllowSegments" type="{}Boolean" minOccurs="0"/>
 *         &lt;element name="DynamicFields" type="{}DynamicFields" minOccurs="0"/>
 *         &lt;element name="Classifications" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Classification" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{}LongCode"/>
 *                             &lt;element name="Code" type="{}LongCode"/>
 *                             &lt;element name="DateRange" type="{}DateTimeRange"/>
 *                             &lt;element name="Comments" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;>ShortComment">
 *                                     &lt;attGroup ref="{}TranslAttrGroup"/>
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StaffMembers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StaffMember" type="{}StaffMemberInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PkgDefinition", propOrder = {

})
public class PkgDefinition {

    @XmlElement(name = "PackageID")
    protected int packageID;
    @XmlElement(name = "Vacation", required = true)
    protected DateTimeRange vacation;
    @XmlElement(name = "Location")
    protected LocationRange location;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "ProductType", required = true)
    protected String productType;
    @XmlElement(name = "SailID")
    protected Integer sailID;
    @XmlElement(name = "LandDays")
    protected BigInteger landDays;
    @XmlElement(name = "SailDays")
    protected BigInteger sailDays;
    @XmlElement(name = "PrePostMode")
    protected String prePostMode;
    @XmlElement(name = "TransfersOnly", defaultValue = "N")
    protected Boolean transfersOnly;
    @XmlElement(name = "NeedsVendorConfirm")
    protected Boolean needsVendorConfirm;
    @XmlElement(name = "Destination")
    protected String destination;
    @XmlElement(name = "Destinations")
    protected PkgDefinition.Destinations destinations;
    @XmlElement(name = "Season")
    protected String season;
    @XmlElement(name = "PkgComment")
    protected PkgDefinition.PkgComment pkgComment;
    @XmlElement(name = "PkgTypeComment")
    protected PkgDefinition.PkgTypeComment pkgTypeComment;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Components")
    protected PkgDefinition.Components components;
    @XmlElement(name = "IsActive", required = true)
    protected Boolean isActive;
    @XmlElement(name = "IsFake")
    protected Boolean isFake;
    @XmlElement(name = "ColorFIT")
    protected String colorFIT;
    @XmlElement(name = "ColorGroup")
    protected String colorGroup;
    @XmlElement(name = "Colors")
    protected PkgDefinition.Colors colors;
    @XmlElement(name = "ShorexMode")
    protected PkgBookMode shorexMode;
    @XmlElement(name = "ShorexTiming")
    protected String shorexTiming;
    @XmlElement(name = "InitialStatus")
    protected PkgStatus initialStatus;
    @XmlElement(name = "AllowSegments", defaultValue = "N")
    protected Boolean allowSegments;
    @XmlElement(name = "DynamicFields")
    protected DynamicFields dynamicFields;
    @XmlElement(name = "Classifications")
    protected PkgDefinition.Classifications classifications;
    @XmlElement(name = "StaffMembers")
    protected PkgDefinition.StaffMembers staffMembers;

    /**
     * Gets the value of the packageID property.
     * 
     */
    public int getPackageID() {
        return packageID;
    }

    /**
     * Sets the value of the packageID property.
     * 
     */
    public void setPackageID(int value) {
        this.packageID = value;
    }

    /**
     * Gets the value of the vacation property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRange }
     *     
     */
    public DateTimeRange getVacation() {
        return vacation;
    }

    /**
     * Sets the value of the vacation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRange }
     *     
     */
    public void setVacation(DateTimeRange value) {
        this.vacation = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationRange }
     *     
     */
    public LocationRange getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationRange }
     *     
     */
    public void setLocation(LocationRange value) {
        this.location = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the sailID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSailID() {
        return sailID;
    }

    /**
     * Sets the value of the sailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSailID(Integer value) {
        this.sailID = value;
    }

    /**
     * Gets the value of the landDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLandDays() {
        return landDays;
    }

    /**
     * Sets the value of the landDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLandDays(BigInteger value) {
        this.landDays = value;
    }

    /**
     * Gets the value of the sailDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSailDays() {
        return sailDays;
    }

    /**
     * Sets the value of the sailDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSailDays(BigInteger value) {
        this.sailDays = value;
    }

    /**
     * Gets the value of the prePostMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrePostMode() {
        return prePostMode;
    }

    /**
     * Sets the value of the prePostMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrePostMode(String value) {
        this.prePostMode = value;
    }

    /**
     * Gets the value of the transfersOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getTransfersOnly() {
        return transfersOnly;
    }

    /**
     * Sets the value of the transfersOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransfersOnly(Boolean value) {
        this.transfersOnly = value;
    }

    /**
     * Gets the value of the needsVendorConfirm property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getNeedsVendorConfirm() {
        return needsVendorConfirm;
    }

    /**
     * Sets the value of the needsVendorConfirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeedsVendorConfirm(Boolean value) {
        this.needsVendorConfirm = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the destinations property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.Destinations }
     *     
     */
    public PkgDefinition.Destinations getDestinations() {
        return destinations;
    }

    /**
     * Sets the value of the destinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.Destinations }
     *     
     */
    public void setDestinations(PkgDefinition.Destinations value) {
        this.destinations = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeason(String value) {
        this.season = value;
    }

    /**
     * Gets the value of the pkgComment property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.PkgComment }
     *     
     */
    public PkgDefinition.PkgComment getPkgComment() {
        return pkgComment;
    }

    /**
     * Sets the value of the pkgComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.PkgComment }
     *     
     */
    public void setPkgComment(PkgDefinition.PkgComment value) {
        this.pkgComment = value;
    }

    /**
     * Gets the value of the pkgTypeComment property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.PkgTypeComment }
     *     
     */
    public PkgDefinition.PkgTypeComment getPkgTypeComment() {
        return pkgTypeComment;
    }

    /**
     * Sets the value of the pkgTypeComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.PkgTypeComment }
     *     
     */
    public void setPkgTypeComment(PkgDefinition.PkgTypeComment value) {
        this.pkgTypeComment = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.Components }
     *     
     */
    public PkgDefinition.Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.Components }
     *     
     */
    public void setComponents(PkgDefinition.Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsActive(Boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isFake property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsFake() {
        return isFake;
    }

    /**
     * Sets the value of the isFake property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFake(Boolean value) {
        this.isFake = value;
    }

    /**
     * Gets the value of the colorFIT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorFIT() {
        return colorFIT;
    }

    /**
     * Sets the value of the colorFIT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorFIT(String value) {
        this.colorFIT = value;
    }

    /**
     * Gets the value of the colorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorGroup() {
        return colorGroup;
    }

    /**
     * Sets the value of the colorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorGroup(String value) {
        this.colorGroup = value;
    }

    /**
     * Gets the value of the colors property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.Colors }
     *     
     */
    public PkgDefinition.Colors getColors() {
        return colors;
    }

    /**
     * Sets the value of the colors property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.Colors }
     *     
     */
    public void setColors(PkgDefinition.Colors value) {
        this.colors = value;
    }

    /**
     * Gets the value of the shorexMode property.
     * 
     * @return
     *     possible object is
     *     {@link PkgBookMode }
     *     
     */
    public PkgBookMode getShorexMode() {
        return shorexMode;
    }

    /**
     * Sets the value of the shorexMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgBookMode }
     *     
     */
    public void setShorexMode(PkgBookMode value) {
        this.shorexMode = value;
    }

    /**
     * Gets the value of the shorexTiming property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShorexTiming() {
        return shorexTiming;
    }

    /**
     * Sets the value of the shorexTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShorexTiming(String value) {
        this.shorexTiming = value;
    }

    /**
     * Gets the value of the initialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PkgStatus }
     *     
     */
    public PkgStatus getInitialStatus() {
        return initialStatus;
    }

    /**
     * Sets the value of the initialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgStatus }
     *     
     */
    public void setInitialStatus(PkgStatus value) {
        this.initialStatus = value;
    }

    /**
     * Gets the value of the allowSegments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAllowSegments() {
        return allowSegments;
    }

    /**
     * Sets the value of the allowSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSegments(Boolean value) {
        this.allowSegments = value;
    }

    /**
     * Gets the value of the dynamicFields property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicFields }
     *     
     */
    public DynamicFields getDynamicFields() {
        return dynamicFields;
    }

    /**
     * Sets the value of the dynamicFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicFields }
     *     
     */
    public void setDynamicFields(DynamicFields value) {
        this.dynamicFields = value;
    }

    /**
     * Gets the value of the classifications property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.Classifications }
     *     
     */
    public PkgDefinition.Classifications getClassifications() {
        return classifications;
    }

    /**
     * Sets the value of the classifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.Classifications }
     *     
     */
    public void setClassifications(PkgDefinition.Classifications value) {
        this.classifications = value;
    }

    /**
     * Gets the value of the staffMembers property.
     * 
     * @return
     *     possible object is
     *     {@link PkgDefinition.StaffMembers }
     *     
     */
    public PkgDefinition.StaffMembers getStaffMembers() {
        return staffMembers;
    }

    /**
     * Sets the value of the staffMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkgDefinition.StaffMembers }
     *     
     */
    public void setStaffMembers(PkgDefinition.StaffMembers value) {
        this.staffMembers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Classification" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Type" type="{}LongCode"/>
     *                   &lt;element name="Code" type="{}LongCode"/>
     *                   &lt;element name="DateRange" type="{}DateTimeRange"/>
     *                   &lt;element name="Comments" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;>ShortComment">
     *                           &lt;attGroup ref="{}TranslAttrGroup"/>
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classification"
    })
    public static class Classifications {

        @XmlElement(name = "Classification")
        protected List<PkgDefinition.Classifications.Classification> classification;

        /**
         * Gets the value of the classification property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classification property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassification().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PkgDefinition.Classifications.Classification }
         * 
         * 
         */
        public List<PkgDefinition.Classifications.Classification> getClassification() {
            if (classification == null) {
                classification = new ArrayList<PkgDefinition.Classifications.Classification>();
            }
            return this.classification;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Type" type="{}LongCode"/>
         *         &lt;element name="Code" type="{}LongCode"/>
         *         &lt;element name="DateRange" type="{}DateTimeRange"/>
         *         &lt;element name="Comments" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;>ShortComment">
         *                 &lt;attGroup ref="{}TranslAttrGroup"/>
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "code",
            "dateRange",
            "comments"
        })
        public static class Classification {

            @XmlElement(name = "Type", required = true)
            protected String type;
            @XmlElement(name = "Code", required = true)
            protected String code;
            @XmlElement(name = "DateRange", required = true)
            protected DateTimeRange dateRange;
            @XmlElement(name = "Comments")
            protected PkgDefinition.Classifications.Classification.Comments comments;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the dateRange property.
             * 
             * @return
             *     possible object is
             *     {@link DateTimeRange }
             *     
             */
            public DateTimeRange getDateRange() {
                return dateRange;
            }

            /**
             * Sets the value of the dateRange property.
             * 
             * @param value
             *     allowed object is
             *     {@link DateTimeRange }
             *     
             */
            public void setDateRange(DateTimeRange value) {
                this.dateRange = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link PkgDefinition.Classifications.Classification.Comments }
             *     
             */
            public PkgDefinition.Classifications.Classification.Comments getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link PkgDefinition.Classifications.Classification.Comments }
             *     
             */
            public void setComments(PkgDefinition.Classifications.Classification.Comments value) {
                this.comments = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;>ShortComment">
             *       &lt;attGroup ref="{}TranslAttrGroup"/>
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Comments {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "Language")
                protected String language;
                @XmlAttribute(name = "Translation")
                protected String translation;

                /**
                 * Short comment.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the language property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguage() {
                    return language;
                }

                /**
                 * Sets the value of the language property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguage(String value) {
                    this.language = value;
                }

                /**
                 * Gets the value of the translation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTranslation() {
                    return translation;
                }

                /**
                 * Sets the value of the translation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTranslation(String value) {
                    this.translation = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Color" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DateRange" type="{}DateRange"/>
     *                   &lt;choice>
     *                     &lt;element name="ColorFIT" minOccurs="0">
     *                       &lt;simpleType>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                           &lt;maxLength value="15"/>
     *                           &lt;whiteSpace value="collapse"/>
     *                         &lt;/restriction>
     *                       &lt;/simpleType>
     *                     &lt;/element>
     *                     &lt;element name="ColorGroup" minOccurs="0">
     *                       &lt;simpleType>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                           &lt;maxLength value="15"/>
     *                           &lt;whiteSpace value="collapse"/>
     *                         &lt;/restriction>
     *                       &lt;/simpleType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                   &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "color"
    })
    public static class Colors {

        @XmlElement(name = "Color")
        protected List<PkgDefinition.Colors.Color> color;

        /**
         * Gets the value of the color property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the color property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getColor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PkgDefinition.Colors.Color }
         * 
         * 
         */
        public List<PkgDefinition.Colors.Color> getColor() {
            if (color == null) {
                color = new ArrayList<PkgDefinition.Colors.Color>();
            }
            return this.color;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DateRange" type="{}DateRange"/>
         *         &lt;choice>
         *           &lt;element name="ColorFIT" minOccurs="0">
         *             &lt;simpleType>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                 &lt;maxLength value="15"/>
         *                 &lt;whiteSpace value="collapse"/>
         *               &lt;/restriction>
         *             &lt;/simpleType>
         *           &lt;/element>
         *           &lt;element name="ColorGroup" minOccurs="0">
         *             &lt;simpleType>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                 &lt;maxLength value="15"/>
         *                 &lt;whiteSpace value="collapse"/>
         *               &lt;/restriction>
         *             &lt;/simpleType>
         *           &lt;/element>
         *         &lt;/choice>
         *         &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dateRange",
            "colorFIT",
            "colorGroup",
            "comments"
        })
        public static class Color {

            @XmlElement(name = "DateRange", required = true)
            protected DateRange dateRange;
            @XmlElement(name = "ColorFIT")
            protected String colorFIT;
            @XmlElement(name = "ColorGroup")
            protected String colorGroup;
            @XmlElement(name = "Comments")
            protected String comments;

            /**
             * Gets the value of the dateRange property.
             * 
             * @return
             *     possible object is
             *     {@link DateRange }
             *     
             */
            public DateRange getDateRange() {
                return dateRange;
            }

            /**
             * Sets the value of the dateRange property.
             * 
             * @param value
             *     allowed object is
             *     {@link DateRange }
             *     
             */
            public void setDateRange(DateRange value) {
                this.dateRange = value;
            }

            /**
             * Gets the value of the colorFIT property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColorFIT() {
                return colorFIT;
            }

            /**
             * Sets the value of the colorFIT property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColorFIT(String value) {
                this.colorFIT = value;
            }

            /**
             * Gets the value of the colorGroup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColorGroup() {
                return colorGroup;
            }

            /**
             * Sets the value of the colorGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColorGroup(String value) {
                this.colorGroup = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Component" type="{}PkgComponent" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "component"
    })
    public static class Components {

        @XmlElement(name = "Component")
        protected List<PkgComponent> component;

        /**
         * Gets the value of the component property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the component property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComponent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PkgComponent }
         * 
         * 
         */
        public List<PkgComponent> getComponent() {
            if (component == null) {
                component = new ArrayList<PkgComponent>();
            }
            return this.component;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Destination" type="{}DestinationCode" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destination"
    })
    public static class Destinations {

        @XmlElement(name = "Destination")
        protected List<String> destination;

        /**
         * Gets the value of the destination property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the destination property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDestination().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDestination() {
            if (destination == null) {
                destination = new ArrayList<String>();
            }
            return this.destination;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>ShortComment">
     *       &lt;attGroup ref="{}TranslAttrGroup"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PkgComment {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Language")
        protected String language;
        @XmlAttribute(name = "Translation")
        protected String translation;

        /**
         * Short comment.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the translation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranslation() {
            return translation;
        }

        /**
         * Sets the value of the translation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranslation(String value) {
            this.translation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>ShortComment">
     *       &lt;attGroup ref="{}TranslAttrGroup"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PkgTypeComment {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Language")
        protected String language;
        @XmlAttribute(name = "Translation")
        protected String translation;

        /**
         * Short comment.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the translation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranslation() {
            return translation;
        }

        /**
         * Sets the value of the translation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranslation(String value) {
            this.translation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StaffMember" type="{}StaffMemberInfo" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "staffMember"
    })
    public static class StaffMembers {

        @XmlElement(name = "StaffMember")
        protected List<StaffMemberInfo> staffMember;

        /**
         * Gets the value of the staffMember property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the staffMember property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStaffMember().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StaffMemberInfo }
         * 
         * 
         */
        public List<StaffMemberInfo> getStaffMember() {
            if (staffMember == null) {
                staffMember = new ArrayList<StaffMemberInfo>();
            }
            return this.staffMember;
        }

    }

}
