//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResChargeState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResChargeState">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="ACTIVE"/>
 *     &lt;enumeration value="VOIDED"/>
 *     &lt;enumeration value="DEFERRED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResChargeState")
@XmlEnum
public enum ResChargeState {

    ACTIVE,
    VOIDED,
    DEFERRED;

    public String value() {
        return name();
    }

    public static ResChargeState fromValue(String v) {
        return valueOf(v);
    }

}
