//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="2"/>
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="SH"/>
 *     &lt;enumeration value="OF"/>
 *     &lt;enumeration value="BK"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="TM"/>
 *     &lt;enumeration value="CX"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="QT"/>
 *     &lt;enumeration value="WL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResStatus")
@XmlEnum
public enum ResStatus {


    /**
     * Shopped - reservation is in process of shopping, is created in
     * 						temporary storage only and not stored in the database
     * 						yet.
     * 
     */
    SH,

    /**
     * Offerred - reservation is created (inventory is guaranteed) but
     * 						not payed yet.
     * 
     */
    OF,

    /**
     * Booked - reservation is created and payed (either full or even
     * 						partially).
     * 
     */
    BK,

    /**
     * Closed - reservation is closed because all purchased services
     * 						were provided (voyage is done, etc).
     * 
     */
    CL,

    /**
     * Terminated - all accounting operations releated to this
     * 						reservation are completed.
     * 
     */
    TM,

    /**
     * Canceled - reservation is canceled.
     * 
     */
    CX,

    /**
     * Canceled Terminated - all accounting operations releated to
     * 						this canceled reservation are completed (there are could be some charges,
     * 						cancelation fees, etc).
     * 
     */
    CT,

    /**
     * Quoted - is not used anymore.
     * 
     */
    QT,

    /**
     * Waitlisted - reservation is done but there is no available
     * 						inventory.
     * 
     */
    WL;

    public String value() {
        return name();
    }

    public static ResStatus fromValue(String v) {
        return valueOf(v);
    }

}
