//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Sail Activity information
 * 
 * <p>Java class for SailActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SailActivity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="SailActivityID" type="{}RecordID"/>
 *         &lt;element name="SailRefID" type="{}RecordID" minOccurs="0"/>
 *         &lt;element name="Ship" type="{}ShipCode"/>
 *         &lt;element name="ActivityType" type="{}SailActivityType"/>
 *         &lt;element name="DateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MayEmbark" type="{}Boolean"/>
 *         &lt;element name="MayDisembark" type="{}Boolean"/>
 *         &lt;element name="Port" type="{}PortCode" minOccurs="0"/>
 *         &lt;element name="Pier" type="{}PierCode" minOccurs="0"/>
 *         &lt;element name="TenderMode" type="{}SailActivityTenderMode" minOccurs="0"/>
 *         &lt;element name="Description" type="{}ShortComment" minOccurs="0"/>
 *         &lt;element name="Notes" type="{}LongComment" minOccurs="0"/>
 *         &lt;element name="Ownership" type="{}OwnershipCode" minOccurs="0"/>
 *         &lt;element name="DressCode" type="{}DressCode" minOccurs="0"/>
 *         &lt;element name="DynamicFields" type="{}DynamicFields" minOccurs="0"/>
 *         &lt;element name="Comments" type="{}ShortComment" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SailActivity", propOrder = {

})
public class SailActivity {

    @XmlElement(name = "SailActivityID")
    protected int sailActivityID;
    @XmlElement(name = "SailRefID")
    protected Integer sailRefID;
    @XmlElement(name = "Ship", required = true)
    protected String ship;
    @XmlElement(name = "ActivityType", required = true)
    protected String activityType;
    @XmlElement(name = "DateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlElement(name = "MayEmbark", required = true)
    protected Boolean mayEmbark;
    @XmlElement(name = "MayDisembark", required = true)
    protected Boolean mayDisembark;
    @XmlElement(name = "Port")
    protected String port;
    @XmlElement(name = "Pier")
    protected String pier;
    @XmlElement(name = "TenderMode")
    protected SailActivityTenderMode tenderMode;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Ownership")
    protected String ownership;
    @XmlElement(name = "DressCode")
    protected String dressCode;
    @XmlElement(name = "DynamicFields")
    protected DynamicFields dynamicFields;
    @XmlElement(name = "Comments")
    protected String comments;

    /**
     * Gets the value of the sailActivityID property.
     * 
     */
    public int getSailActivityID() {
        return sailActivityID;
    }

    /**
     * Sets the value of the sailActivityID property.
     * 
     */
    public void setSailActivityID(int value) {
        this.sailActivityID = value;
    }

    /**
     * Gets the value of the sailRefID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSailRefID() {
        return sailRefID;
    }

    /**
     * Sets the value of the sailRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSailRefID(Integer value) {
        this.sailRefID = value;
    }

    /**
     * Gets the value of the ship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShip() {
        return ship;
    }

    /**
     * Sets the value of the ship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShip(String value) {
        this.ship = value;
    }

    /**
     * Gets the value of the activityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityType(String value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the mayEmbark property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMayEmbark() {
        return mayEmbark;
    }

    /**
     * Sets the value of the mayEmbark property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMayEmbark(Boolean value) {
        this.mayEmbark = value;
    }

    /**
     * Gets the value of the mayDisembark property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMayDisembark() {
        return mayDisembark;
    }

    /**
     * Sets the value of the mayDisembark property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMayDisembark(Boolean value) {
        this.mayDisembark = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the pier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPier() {
        return pier;
    }

    /**
     * Sets the value of the pier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPier(String value) {
        this.pier = value;
    }

    /**
     * Gets the value of the tenderMode property.
     * 
     * @return
     *     possible object is
     *     {@link SailActivityTenderMode }
     *     
     */
    public SailActivityTenderMode getTenderMode() {
        return tenderMode;
    }

    /**
     * Sets the value of the tenderMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailActivityTenderMode }
     *     
     */
    public void setTenderMode(SailActivityTenderMode value) {
        this.tenderMode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the ownership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnership() {
        return ownership;
    }

    /**
     * Sets the value of the ownership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnership(String value) {
        this.ownership = value;
    }

    /**
     * Gets the value of the dressCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDressCode() {
        return dressCode;
    }

    /**
     * Sets the value of the dressCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDressCode(String value) {
        this.dressCode = value;
    }

    /**
     * Gets the value of the dynamicFields property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicFields }
     *     
     */
    public DynamicFields getDynamicFields() {
        return dynamicFields;
    }

    /**
     * Sets the value of the dynamicFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicFields }
     *     
     */
    public void setDynamicFields(DynamicFields value) {
        this.dynamicFields = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
