//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sail boundaries to be used in input messages
 * 
 * <p>Java class for SailRangeInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SailRangeInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ship" type="{}ShipCode" minOccurs="0"/>
 *         &lt;element name="TimePrecision" type="{}SailTimePrecision" minOccurs="0"/>
 *         &lt;element name="From" type="{}SailRefInput"/>
 *         &lt;element name="To" type="{}SailRefInput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SailRangeInput", propOrder = {
    "ship",
    "timePrecision",
    "from",
    "to"
})
public class SailRangeInput {

    @XmlElement(name = "Ship")
    protected String ship;
    @XmlElement(name = "TimePrecision")
    protected BigInteger timePrecision;
    @XmlElement(name = "From", required = true)
    protected SailRefInput from;
    @XmlElement(name = "To", required = true)
    protected SailRefInput to;

    /**
     * Gets the value of the ship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShip() {
        return ship;
    }

    /**
     * Sets the value of the ship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShip(String value) {
        this.ship = value;
    }

    /**
     * Gets the value of the timePrecision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimePrecision() {
        return timePrecision;
    }

    /**
     * Sets the value of the timePrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimePrecision(BigInteger value) {
        this.timePrecision = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link SailRefInput }
     *     
     */
    public SailRefInput getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailRefInput }
     *     
     */
    public void setFrom(SailRefInput value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link SailRefInput }
     *     
     */
    public SailRefInput getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailRefInput }
     *     
     */
    public void setTo(SailRefInput value) {
        this.to = value;
    }

}
