//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Sail boundaries with optional nodes
 * 
 * <p>Java class for SailRangeOptional complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SailRangeOptional">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ship" type="{}ShipCode" minOccurs="0"/>
 *         &lt;element name="From" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DateTime" type="{}SailDateTime" minOccurs="0"/>
 *                   &lt;element name="SailRefID" type="{}RecordID" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="To" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DateTime" type="{}SailDateTime" minOccurs="0"/>
 *                   &lt;element name="SailRefID" type="{}RecordID" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PortFrom" type="{}PortCode" minOccurs="0"/>
 *         &lt;element name="PortTo" type="{}PortCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SailRangeOptional", propOrder = {
    "ship",
    "from",
    "to",
    "portFrom",
    "portTo"
})
public class SailRangeOptional {

    @XmlElement(name = "Ship")
    protected String ship;
    @XmlElement(name = "From")
    protected SailRangeOptional.From from;
    @XmlElement(name = "To")
    protected SailRangeOptional.To to;
    @XmlElement(name = "PortFrom")
    protected String portFrom;
    @XmlElement(name = "PortTo")
    protected String portTo;

    /**
     * Gets the value of the ship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShip() {
        return ship;
    }

    /**
     * Sets the value of the ship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShip(String value) {
        this.ship = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link SailRangeOptional.From }
     *     
     */
    public SailRangeOptional.From getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailRangeOptional.From }
     *     
     */
    public void setFrom(SailRangeOptional.From value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link SailRangeOptional.To }
     *     
     */
    public SailRangeOptional.To getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailRangeOptional.To }
     *     
     */
    public void setTo(SailRangeOptional.To value) {
        this.to = value;
    }

    /**
     * Gets the value of the portFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortFrom() {
        return portFrom;
    }

    /**
     * Sets the value of the portFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortFrom(String value) {
        this.portFrom = value;
    }

    /**
     * Gets the value of the portTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortTo() {
        return portTo;
    }

    /**
     * Sets the value of the portTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortTo(String value) {
        this.portTo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DateTime" type="{}SailDateTime" minOccurs="0"/>
     *         &lt;element name="SailRefID" type="{}RecordID" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateTime",
        "sailRefID"
    })
    public static class From {

        @XmlElement(name = "DateTime")
        protected XMLGregorianCalendar dateTime;
        @XmlElement(name = "SailRefID")
        protected Integer sailRefID;

        /**
         * Gets the value of the dateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateTime() {
            return dateTime;
        }

        /**
         * Sets the value of the dateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateTime(XMLGregorianCalendar value) {
            this.dateTime = value;
        }

        /**
         * Gets the value of the sailRefID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSailRefID() {
            return sailRefID;
        }

        /**
         * Sets the value of the sailRefID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSailRefID(Integer value) {
            this.sailRefID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DateTime" type="{}SailDateTime" minOccurs="0"/>
     *         &lt;element name="SailRefID" type="{}RecordID" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateTime",
        "sailRefID"
    })
    public static class To {

        @XmlElement(name = "DateTime")
        protected XMLGregorianCalendar dateTime;
        @XmlElement(name = "SailRefID")
        protected Integer sailRefID;

        /**
         * Gets the value of the dateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateTime() {
            return dateTime;
        }

        /**
         * Sets the value of the dateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateTime(XMLGregorianCalendar value) {
            this.dateTime = value;
        }

        /**
         * Gets the value of the sailRefID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSailRefID() {
            return sailRefID;
        }

        /**
         * Sets the value of the sailRefID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSailRefID(Integer value) {
            this.sailRefID = value;
        }

    }

}
