//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 03:39:13 PM IST 
//


package com.virginvoyages.seaware.xml.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellLimBasis.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SellLimBasis">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="20"/>
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="PKG/GUEST"/>
 *     &lt;enumeration value="GUEST"/>
 *     &lt;enumeration value="PKG/RES"/>
 *     &lt;enumeration value="CABIN"/>
 *     &lt;enumeration value="RES"/>
 *     &lt;enumeration value="ROOM"/>
 *     &lt;enumeration value="DINING"/>
 *     &lt;enumeration value="DINING_GUEST"/>
 *     &lt;enumeration value="CARREQ"/>
 *     &lt;enumeration value="CARLEG"/>
 *     &lt;enumeration value="CAR LENGTH"/>
 *     &lt;enumeration value="ADJUSTED LENGTH"/>
 *     &lt;enumeration value="SHIPROOM"/>
 *     &lt;enumeration value="SHIPROOM_GUEST"/>
 *     &lt;enumeration value="ADDON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SellLimBasis")
@XmlEnum
public enum SellLimBasis {

    @XmlEnumValue("PKG/GUEST")
    PKG_GUEST("PKG/GUEST"),
    GUEST("GUEST"),
    @XmlEnumValue("PKG/RES")
    PKG_RES("PKG/RES"),
    CABIN("CABIN"),
    RES("RES"),
    ROOM("ROOM"),
    DINING("DINING"),
    DINING_GUEST("DINING_GUEST"),
    CARREQ("CARREQ"),
    CARLEG("CARLEG"),
    @XmlEnumValue("CAR LENGTH")
    CAR_LENGTH("CAR LENGTH"),
    @XmlEnumValue("ADJUSTED LENGTH")
    ADJUSTED_LENGTH("ADJUSTED LENGTH"),
    SHIPROOM("SHIPROOM"),
    SHIPROOM_GUEST("SHIPROOM_GUEST"),
    ADDON("ADDON");
    private final String value;

    SellLimBasis(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SellLimBasis fromValue(String v) {
        for (SellLimBasis c: SellLimBasis.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
